### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by minkyukang707** [SkoltechAI/fewbit#4]
I have an issue on installation 

i saw previous installation error and i used that command line 

!pip install -U git+https://github.com/SkoltechAI/fewbit.git

but i got this error 

**from anaconda** 
(mintorch0208) C:\Users\user>pip install -U git+https://github.com/SkoltechAI/fewbit.git
WARNING: Ignoring invalid distribution -ywin32 (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -oundfile (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ywin32 (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -oundfile (c:\users\user\appdata\roaming\python\python38\site-packages)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/SkoltechAI/fewbit.git
  Cloning https://github.com/SkoltechAI/fewbit.git to c:\users\user\appdata\local\temp\pip-req-build-yiimezc5
  ERROR: Error [WinError 2] 지정된 파일을 찾을 수 없습니다 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
WARNING: Ignoring invalid distribution -ywin32 (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -oundfile (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ywin32 (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -oundfile (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ywin32 (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\user\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -oundfile (c:\users\user\appdata\roaming\python\python38\site-packages)

**from google colab** 
Collecting git+https://github.com/SkoltechAI/fewbit.git
  Cloning https://github.com/SkoltechAI/fewbit.git to /tmp/pip-req-build-5o0y_v8o
  Running command git clone --filter=blob:none --quiet https://github.com/SkoltechAI/fewbit.git /tmp/pip-req-build-5o0y_v8o
  Resolved https://github.com/SkoltechAI/fewbit.git to commit 940706bbbc40b11ade61d42253f80dc960d35793
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

May i get some help?

**Comment by daskol** [comment]
It seems that you didn't have `git` installed (`git+https` means that the packaged should be fetched with `git` and install from cloned repo`).
